version: '3.8'

services:
  app:
    container_name: java-spring
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./entrypoint.sh
    volumes:
        - .:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8443
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local