version: '3.8'

services:
  app:
    container_name: java-spring
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./entrypoint.sh
    volumes:
        - .:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8443

